version: "3.8"

services:
  client:
    image: faceless-client
    ports:
      - "3001:3001"
    depends_on:
      - server
      - redis

  server:
    image: faceless-server
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
