// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");

Jest.describe("test0", (function (param) {
        return Jest.test("some test does this...", (function (param) {
                      return Jest.Expect.toBe(11, Jest.Expect.expect(10));
                    }));
      }));

/*  Not a pure module */
